baseurl = "https://www.prioritydetails.com/"
relativeurls = true
languageCode = "en-us"
title = "Priority Details"
theme = "Mainroad"
googleAnalytics = "UA-90533434-1"
disqusShortname = "priority-details"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/wangyuchen"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/yuchen0712/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    mathjax = true # Enable MathJax
    mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
    mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
 
    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    [Params.sidebar]
    home = "right" # Configure layout for home page
    list = "left"  # Configure layout for list pages
    single = false # Configure layout for single pages
    # Enable widgets in given order
    widgets = ["linkedin", "recent", "categories", "taglist", "social", "languages"]



    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
