baseurl = "http://www.prioritydetails.com/"
relativeurls = true
languageCode = "en-us"
title = "Priority Details"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-90533434-1"
disqusShortname = "priority-details"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/wangyuchen"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/yuchen0712/"

[params]
    description = "A Blog on top priority details in R and statistics."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

